insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (72009, 'Kite, black', 802, 1);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (82086, 'Arctic tern', 885, 4);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (17365, 'Pale-throated three-toed sloth', 579, 9);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (54963, 'Stork, yellow-billed', 356, 5);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (91392, 'Old world fruit bat (unidentified)', 336, 9);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (36152, 'Wallaby, river', 597, 18);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (72309, 'Toucan, red-billed', 341, 18);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (26465, 'Small Indian mongoose', 23, 18);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (48870, 'Asian water dragon', 485, 13);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (16814, 'Anteater, australian spiny', 557, 11);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (27405, 'Gorilla, western lowland', 819, 9);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (33543, 'African buffalo', 637, 18);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (74390, 'Madagascar fruit bat', 458, 16);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (62816, 'Macaque, pig-tailed', 502, 4);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (31712, 'Slender loris', 307, 3);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (5196, 'Lapwing (unidentified)', 560, 16);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (38181, 'Swan, black', 824, 3);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (39365, 'Nine-banded armadillo', 634, 16);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (89664, 'Caracara (unidentified)', 315, 6);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (40585, 'Lizard, frilled', 359, 11);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (38789, 'Brown hyena', 448, 7);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (45989, 'Great horned owl', 837, 12);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (82715, 'Asian water buffalo', 659, 12);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (94802, 'Pygmy possum', 963, 17);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (5241, 'Old world fruit bat (unidentified)', 569, 11);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (9221, 'Tailless tenrec', 17, 17);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (45012, 'Grenadier, common', 838, 8);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (84277, 'Capybara', 378, 11);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (38113, 'Dove, mourning collared', 897, 2);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (75724, 'Lemur, grey mouse', 908, 7);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (22231, 'Common dolphin', 978, 19);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (73243, 'Goose, snow', 400, 13);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (21498, 'Owl, great horned', 525, 12);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (20917, 'Tree porcupine', 256, 13);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (46507, 'Kaffir cat', 775, 16);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (63508, 'Wild turkey', 953, 12);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (97520, 'Parrot, hawk-headed', 841, 17);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (23235, 'Yak', 956, 6);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (88272, 'Deer, black-tailed', 883, 2);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (3619, 'American bighorn sheep', 228, 14);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (67348, 'Booby, masked', 779, 4);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (77710, 'Beaver, european', 532, 18);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (88113, 'Pie, indian tree', 489, 13);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (83959, 'Bird, black-throated butcher', 447, 14);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (80553, 'Oystercatcher, blackish', 872, 7);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (3112, 'Flamingo, lesser', 174, 1);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (64316, 'Javan gold-spotted mongoose', 23, 10);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (24648, 'White-faced tree rat', 237, 4);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (19985, 'Pademelon, red-legged', 916, 5);
insert into Transactions (trx_amount, trx_description, trx_cust_id, trx_mgr_id) values (40590, 'Fox, bat-eared', 111, 3);
